### ISSUE TITLE
On mobile, our names in About section of the website is written vertically.

### ISSUE THREAD

**Issue by izzagilani** [worklark/worklark#2]
![Screenshot_20190924-165349_Chrome](https://user-images.githubusercontent.com/38578788/65509591-4010c600-deec-11e9-86d1-e71c690af3f5.jpg)
Please find the attachment regarding this issue. Thanks

**Comment by amingilani** [comment]
What's the issue?

**Comment by izzagilani** [comment]
Can the name be written horizontally like this; see attachment.
![Screen Shot 2019-09-24 at 5 02 38 PM](https://user-images.githubusercontent.com/38578788/65509965-28860d00-deed-11e9-9720-0d2ca3a6aa58.png)

**Comment by amingilani** [comment]
I've just discovered that the fonts weren't even loading on mobile. It appears that the CSS rule to import the fonts was incorrectly implemented in the following lines: https://github.com/worklark/worklark/blob/6dbe43b911ee54124af974e4385dc41328714823/app/assets/stylesheets/static_pages.scss#L49 https://github.com/worklark/worklark/blob/6dbe43b911ee54124af974e4385dc41328714823/app/assets/stylesheets/static_pages.scss#L55

This means no one apart from me was seeing the right fonts at all unless, like me, they had the fonts installed on their system.

**Comment by amingilani** [comment]
Font import was fixed in 55e8038f82d370c6cd0f5ba8b6a8b22242928b9d
